### ISSUE TITLE
Testing instructions in readme don't seem to work

### ISSUE THREAD

**Issue by rjwright** [css-typed-om/typed-om#78]
$ npm test

> typed-om@1.0.0 test /home/rjwright/TOM/typed-om
> ./node_modules/phantomjs/bin/phantomjs ./node_modules/mocha-phantomjs-core/mocha-phantomjs-core.js ./test/runner.html

sh: ./node_modules/phantomjs/bin/phantomjs: No such file or directory
npm ERR! weird error 127
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! not ok code 0

**Comment by wilddamon** [comment]
I referenced the wrong bug in my PR. Reopening.

**Comment by samthor** [comment]
The issue here partially is because you haven't run `npm install` to get PhantomJS. I'll update the README.

**Comment by samthor** [comment]
Oh, the README includes it already. @rjwright your error looks like it just wasn't installed. If this isn't the case then please reopen.

**Comment by rjwright** [comment]
I just switched to using the test runner.  If it's working for you then we can leave it closed for now.
