### ISSUE TITLE
Is cssText a getter that generates a string?

### ISSUE THREAD

**Issue by trusktr** [css-typed-om/typed-om#85]
Just curious if `.cssText` is supposed to generate a string (so that if it is never used the performance cost is never incurred).

For example, in

``` js
document.querySelector('.example').styleMap.get('background-position').cssText;
```

Does the access of `.cssText` generate the string at the moment? (That's my guess)

**Comment by shans** [comment]
At least in the polyfill, <code>.cssText</code> is just reading the underlying style value, so there's no performance cost incurred by accessing it.

**Comment by trusktr** [comment]
I'm hope the native implementation generates the string value only when `cssText` is accessed, that way if we never access it there's no number-to-string performance cost. And same with the `style` attribute.

**Comment by shans** [comment]
Unless I'm missing something and there's some specification piece that is missing, optimizations like that would be a matter for the various browser developers.

Having said that, performance is a goal of the API so deferring the cost of string conversion until it was necessary makes sense. It's certainly something we'd look at doing in Chrome.
